### ISSUE TITLE
java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1Integer.<init>(I)V

### ISSUE THREAD

**Issue by mahalingam79** [ryantenney/passkit4j#25]
Hi,

I am trying to run the example application.But when i run the program the below exception is occurred.Any idea ?
I am using java 1.6.0_25 with bouncycastle1.47 jars in classpath.

Exception in thread "main" java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1Integer.<init>(I)V
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.createPSSParams(Unknown Source)
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
	at org.bouncycastle.cms.jcajce.JcaSimpleSignerInfoGeneratorBuilder$NamedHelper.createContentSigner(Unknown Source)
	at org.bouncycastle.cms.jcajce.JcaSimpleSignerInfoGeneratorBuilder.build(Unknown Source)
	at com.ryantenney.passkit4j.sign.PassSignerImpl.createGenerator(PassSignerImpl.java:137)
	at com.ryantenney.passkit4j.sign.PassSignerImpl.<init>(PassSignerImpl.java:128)
	at com.ryantenney.passkit4j.sign.PassSignerImpl$Builder.build(PassSignerImpl.java:122)

**Comment by mahalingam79** [comment]
The issue is because of multiple(bouncycastle) jars with different versions.Removed the old entry.Now it is moving forward.
